### ISSUE TITLE
consider aligning with github.com/containers

### ISSUE THREAD

**Issue by cgwalters** [project-machine/puzzlefs#90]
This is just a first quick glance at your code.

- It looks like you have a reimplementation of a subset of [our oci_spec crate](https://docs.rs/oci-spec/latest/oci_spec/) here https://github.com/anuvu/puzzlefs/blob/master/oci/src/lib.rs 
- I have some [oci directory code](https://github.com/ostreedev/ostree-rs-ext/blob/main/lib/src/container/ocidir.rs) that I've been meaning to make into a crate and would be happy to consider sharing as a crate for the non-spec bits of that code

Then bigger picture, we also have https://github.com/containers/composefs - per the kernel discussion thread  we could also try to build a comparison doc and see if there's any common ideas or code we could share.  (I actually want to try to argue to do some composefs tooling in Rust)

**Comment by ariel-miculas** [comment]
@cgwalters do you want to setup a separate repo with your oci directory code? I think that would be a good starting point

**Comment by cgwalters** [comment]
Eventually yeah...

**Comment by ariel-miculas** [comment]
@cgwalters I see the oci directory code is now in its [own crate](https://github.com/containers/ocidir-rs), I'll look into it and see if I can use it in PuzzleFS.

**Comment by cgwalters** [comment]
Yep, though also interested in that bigger picture scoped discussion about composefs vs puzzlefs at some point

**Comment by ariel-miculas** [comment]
@cgwalters I'll be at LPC next week, any chance you're also coming?

**Comment by ariel-miculas** [comment]
With the [integration of the PuzzleFS image into the OCI spec](https://github.com/project-machine/puzzlefs/pull/128/), [my latest PR](https://github.com/project-machine/puzzlefs/pull/134) and [my contributions to ocidir-rs](https://github.com/containers/ocidir-rs/pulls?q=is%3Apr+is%3Aclosed+author%3Aariel-miculas), PuzzleFS now uses [ocidir-rs](https://github.com/containers/ocidir-rs) extensively, so I'm quite happy we manged to align and work towards our common goals, @cgwalters !

Of course, the work doesn't end here, but I'm closing this issue and I'll open another issue/discussion for the bigger picture composefs vs puzzlefs conversation.
